import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            {/* <SignInButton mode="modal" /> */}
            <SignInButton forceRedirectUrl="" />
            {/* <SignInButton>text</SignInButton> */}
          </SignedOut>
          <SignedIn>
            <UserButton showName />
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
